### PR TITLE
Upgrade version of c3p0

### LINKED ISSUE #4: Upgrade version of c3p0
There is an annoying logging issue with the version of c3p0 that is being used; actually a transitive dependency of `mchange-commons-java`. The issue has been resolved and released and should be picked up by newer versions of c3p0.

I've been testing with version `0.9.5.2` of c3p0 and everything seems to be working alright.

Here's the issue that was resolved in c3p0:

https://github.com/swaldman/c3p0/issues/52

### PR DESCRIPTION
**Pull request by bostonaholic**
Fixes #4

### CODE REVIEW

**Comment by samsondav** [comment]
Thanks!!

**Comment by bostonaholic** [comment]
@samphilipd Any idea when a new version will be release so I can pick up this change?

**Comment by samsondav** [comment]
@bostonaholic Sadly probably never, as I no longer use this library or Clojure in my day to day :/ - would you like to become the maintainer of it?

**Comment by bostonaholic** [comment]
@samphilipd I'm sorry to hear that you're not using Clojure as much any longer.

I'd be happy to take over of this library, since I am full-time Clojure, and I have been for a while. And since I'm currently using this lib day-to-day.

Let me know what you need from me to transfer maintainership.

**Comment by samsondav** [comment]
@bostonaholic I can transfer it to you once you have deleted your fork (or renamed it).

Github requires that bostonaholic/clojure.jdbc-c3p0 be available.

**Comment by bostonaholic** [comment]
@samphilipd done.

**Pull request merged**
